# Generated by Django 5.0.7 on 2024-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_total_price_alter_orderitem_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
    ]
