# Generated by Django 5.0.7 on 2024-08-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_discountcode_used_discountcode_used_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='usage_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
