version: '3.9'

services:
  web:
    build: .
    command: ./api-start-prod.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web_plate

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web_plate

volumes:
  postgres_data:

networks:
  web_plate:
